version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: app-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python app.py

  frontend:
    build:
      context: ./frontend
    container_name: app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # コンテナ内の node_modules をホストにかぶせないための“空マウント”
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Vite開発サーバを外部（ホスト）から叩けるように --host を付与
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend